#!/usr/bin/env python
"""
Script to test F1-score for Ariel Sharon with varying n_components in PCA eigenfaces.
Runs the eigenfaces pipeline for each n_components in {10, 15, 25, 50, 100, 250}.
Generated by Deepseek-v3.2-reasoner.
"""

from time import time
import logging
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.datasets import fetch_lfw_people
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.feature_selection import VarianceThreshold

# Set up logging to INFO level
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s')

def run_experiment(n_components):
    """Run eigenfaces pipeline with given n_components, return F1-score for Ariel Sharon."""
    print(f"\n=== Running experiment with n_components = {n_components} ===")

    # Load data
    lfw_people = fetch_lfw_people(min_faces_per_person=70, resize=0.4)
    n_samples, h, w = lfw_people.images.shape
    np.random.seed(42)

    X = lfw_people.data
    y = lfw_people.target
    target_names = lfw_people.target_names
    n_classes = target_names.shape[0]

    # Find index of Ariel Sharon
    try:
        ariel_index = np.where(target_names == 'Ariel Sharon')[0][0]
    except IndexError:
        # In case name doesn't match exactly, try case-insensitive
        for idx, name in enumerate(target_names):
            if 'Ariel' in name or 'Sharon' in name:
                ariel_index = idx
                print(f"Using target name '{name}' for Ariel Sharon (index {ariel_index})")
                break
        else:
            raise ValueError("Could not find 'Ariel Sharon' in target_names")

    # Split into train/test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

    # Variance thresholding
    vt = VarianceThreshold(threshold=1e-10)
    X_train = vt.fit_transform(X_train)
    X_test = vt.transform(X_test)
    n_features = X_train.shape[1]
    print(f"Number of features after variance thresholding: {n_features}")

    # Check n_components <= n_features
    if n_components > n_features:
        print(f"Warning: n_components ({n_components}) > n_features ({n_features}). Setting n_components = n_features.")
        n_components = n_features

    # Check for NaNs
    if np.isnan(X_train).any() or np.isnan(X_test).any():
        raise ValueError("NaN detected in data before PCA")

    # PCA
    print(f"Extracting top {n_components} eigenfaces from {X_train.shape[0]} faces")
    t0 = time()
    pca = PCA(n_components=n_components, whiten=True, svd_solver='full').fit(X_train)
    print(f"PCA done in {time() - t0:.3f}s")

    X_train_pca = pca.transform(X_train)
    X_test_pca = pca.transform(X_test)

    # Check for NaNs after PCA
    if np.isnan(X_train_pca).any() or np.isnan(X_test_pca).any():
        raise ValueError("NaN detected after PCA")

    # SVM with grid search
    print("Fitting SVM classifier with grid search")
    t0 = time()
    param_grid = {
        'C': [1e3, 5e3, 1e4, 5e4, 1e5],
        'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1],
    }
    clf = GridSearchCV(SVC(kernel='rbf', class_weight='balanced'), param_grid)
    clf = clf.fit(X_train_pca, y_train)
    print(f"Grid search done in {time() - t0:.3f}s")
    print(f"Best parameters: {clf.best_params_}")

    # Prediction
    print("Predicting on test set")
    t0 = time()
    y_pred = clf.predict(X_test_pca)
    print(f"Prediction done in {time() - t0:.3f}s")

    # Classification report
    report = classification_report(y_test, y_pred, target_names=target_names, output_dict=True)

    # Extract F1-score for Ariel Sharon
    ariel_report = report[target_names[ariel_index]]
    f1 = ariel_report['f1-score']
    precision = ariel_report['precision']
    recall = ariel_report['recall']

    print(f"Ariel Sharon - Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

    return {
        'n_components': n_components,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'best_params': clf.best_params_,
        'n_features': n_features,
        'variance_explained': pca.explained_variance_ratio_.sum()
    }

def main():
    n_components_list = [10, 15, 25, 50, 100, 250]
    results = []

    for n_comp in n_components_list:
        try:
            result = run_experiment(n_comp)
            results.append(result)
        except Exception as e:
            print(f"Error with n_components={n_comp}: {e}")
            continue

    # Print summary table
    print("\n" + "="*80)
    print("SUMMARY OF RESULTS")
    print("="*80)
    print(f"{'n_components':>12} {'F1-score':>10} {'Precision':>10} {'Recall':>10} {'Features':>10} {'Var Explained':>14}")
    for r in results:
        print(f"{r['n_components']:>12} {r['f1']:>10.4f} {r['precision']:>10.4f} {r['recall']:>10.4f} {r['n_features']:>10} {r['variance_explained']:>14.4f}")

    # Optionally save to CSV
    import csv
    csv_file = 'eigenfaces_results.csv'
    with open(csv_file, 'w', newline='') as f:
        fieldnames = ['n_components', 'f1', 'precision', 'recall', 'best_params', 'n_features', 'variance_explained']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            # Convert best_params dict to string for CSV
            r_copy = r.copy()
            r_copy['best_params'] = str(r['best_params'])
            writer.writerow(r_copy)
    print(f"\nResults saved to {csv_file}")

if __name__ == '__main__':
    main()


"""
================================================================================
SUMMARY OF RESULTS
================================================================================
n_components   F1-score  Precision     Recall   Features  Var Explained
          10     0.1765     0.1429     0.2308       1850         0.6313
          15     0.4516     0.3889     0.5385       1850         0.6945
          25     0.5000     0.4667     0.5385       1850         0.7658
          50     0.7407     0.7143     0.7692       1850         0.8472
         100     0.7200     0.7500     0.6923       1850         0.9158
         250     0.7143     0.6667     0.7692       1850         0.9760
Results saved to eigenfaces_results.csv
"""
